### ISSUE TITLE
Cannot delete accounts

### ISSUE THREAD

**Issue by Padanub** [strideynet/ModelWorld-Bank#109]
As a staff member I'd like the ability to "close" an account by sending all of its money to Nub Banks account and deleting the account with one click

30 minutes

**Comment by strideynet** [comment]
Do we want to retain the account so we can see its tx history, or just delete it entirely?

**Comment by Padanub** [comment]
Delete it entirely, we have no need for historical tx data, unless it's easier to not delete it entirely?
