### ISSUE TITLE
Cannot change account owners/add owners after account creation

### ISSUE THREAD

**Issue by Padanub** [strideynet/ModelWorld-Bank#111]
As a user and a staff member I want to be able to change who can access my account with Read, read/Write settings

Time: 30 minutes

**Comment by Padanub** [comment]
Cannot remove either, there is generally no "account management" page

**Comment by Padanub** [comment]
I removed myself from your account and expected to not see it anymore but it still shows after hard refresh and I still have full access, I also only had "read" ability but can seemingly make transactions

**Comment by strideynet** [comment]
Pretty sure this is working and you are confusing yourself because admins can override and view accounts they dont have acess to
