### ISSUE TITLE
user logging in without account does not throw meaningful error

### ISSUE THREAD

**Issue by sam-irl** [strideynet/ModelWorld-Bank#117]
As a user I'd like to know if I do not have an account when I login, at the moment I just get a blank screen.

Time: 30 Minutes to design and implement a nice page for this

**Comment by strideynet** [comment]
why would there be an error?

**Comment by sam-irl** [comment]
or at least some indication the account doesn't exist -- at present it just directs them to the dashboard with default values and the stacktrace in a red box

**Comment by Padanub** [comment]
Believe fixed
