### ISSUE TITLE
Account flags don't work

### ISSUE THREAD

**Issue by Padanub** [strideynet/ModelWorld-Bank#118]
As Staff I want the account-flags to be working correctly on set-up and be able to be amended post set-up (public/company flag)

**Comment by strideynet** [comment]
Do we want to stay with just Corporate / Personal for now?

**Comment by Padanub** [comment]
Could we investigate https://github.com/strideynet/ModelWorld-Bank/issues/21 adding a "savings" account flag? Similar to corporate (no wages/benefits received)

**Comment by strideynet** [comment]
https://github.com/strideynet/ModelWorld-Bank/issues/128
