### ISSUE TITLE
Account Flags dont seem to work

### ISSUE THREAD

**Issue by Padanub** [strideynet/ModelWorld-Bank#144]
I set the Nub Test account to have the Account Type "Fake Account Test", this account doesn't allow anything (salary etc).

On this account I was still able to request wages and on the admin management panel I was able to approve them. I haven't tried property transfer or betting yet as neither are done. Benefits will be tested tonight I guess

**Comment by Padanub** [comment]
Nub Bank is a system account but now has a property and is getting income from it

**Comment by Padanub** [comment]
As an admin I was able to give a non-property account a property, even though they can't see the property page they still show in their net worth and in their income.

Leaving issue open as I need to test what happens if I transfer a property from a user to a user that can't take properties.

**Comment by strideynet** [comment]
@Padanub Is an admin being able to force a user to own a property actually a problem? I can prevent this but don't come asking for it down the line :)
