### ISSUE TITLE
As a user, I want to see a "Nothing to Display" message in properties.

### ISSUE THREAD

**Issue by adjwood** [strideynet/ModelWorld-Bank#152]
![image](https://user-images.githubusercontent.com/12470650/72255297-47c0bb80-35fe-11ea-97dd-0d5e8eb0436e.png)

Self-explanatory - If I own 0 properties and go to the properties tab, I should see a "no properties owned" or similar message.

**Comment by Padanub** [comment]
Closed, duplicate issue #150

**Comment by adjwood** [comment]
whoops sorry I forgot to check for this first
