### ISSUE TITLE
Wage Screen is blank

### ISSUE THREAD

**Issue by Padanub** [strideynet/ModelWorld-Bank#156]
Tried to go onto wage screen today for Padanub or Strideynet account and it's blank, force refresh doesnt help

![image](https://user-images.githubusercontent.com/20230725/72336719-3ab4d280-36b9-11ea-8d72-27bd75761991.png)

**Comment by adjwood** [comment]
![image](https://user-images.githubusercontent.com/12470650/72336785-57e9a100-36b9-11ea-8ce1-5bcd4373a381.png)

Also occurring on my account - Empty Cache and Hard Reload does not fix

**Comment by Padanub** [comment]
Believe fixed
