### ISSUE TITLE
Account Selector fuckery

### ISSUE THREAD

**Issue by Padanub** [strideynet/ModelWorld-Bank#169]
In the account selector when you choose an account it goes from wherever it is in the list, to the bottom of the list, which is a bit odd, are we able to keep it static or allow people to change it as they wish so they can select the order? I'm not OCD but having the colours in random places is upsetting me

**Comment by adjwood** [comment]
Currently selected account no longer shows up in the account selector - I would say Complete but I will wait till I can perform further testing to Close it.
