### ISSUE TITLE
Turn leaderboard into Net worth rather than cash balance?

### ISSUE THREAD

**Issue by Padanub** [strideynet/ModelWorld-Bank#173]
As the title suggests, lets rank everyone on Net Worth

**Comment by adjwood** [comment]
This makes sense to me - it is how the Forbes richest list works if I remember correctly.

**Comment by adjwood** [comment]
![image](https://user-images.githubusercontent.com/12470650/77367509-39a3bf80-6d52-11ea-9ad0-d7fa8292aa84.png)
Completed by me :)

(with a little help from @strideynet 😛  )
