### ISSUE TITLE
News Page

### ISSUE THREAD

**Issue by Padanub** [strideynet/ModelWorld-Bank#19]
Replace the current homepage with a news page, filled with flavour news and links from MHOC and some news of our own about the financial sector (bank of england rates, general news stuff, I'd be happy to write it).

Gives a more fluid front page, then the original homepage could be an "about page" or something similar

**Comment by strideynet** [comment]
Sounds good if someone wants to write up on an admin panel new posts etc

**Comment by DestinationDemocracyPAC** [comment]
Yeah, if theres an admin panel button to add new posts that'd be good, that way I can quickly crosspost MHOC stuff as filler to bigger news about the site and things

**Comment by Padanub** [comment]
We need a content management system so I can publish to it. Or link it to Saltcon or s/t
