### ISSUE TITLE
Interest Accounts

### ISSUE THREAD

**Issue by Padanub** [strideynet/ModelWorld-Bank#21]
As a user I'd like to be able to earn interest on my savings (savings account) 

As staff I'd like to be able to set an interest rate for savings accounts and have interest paid automatically daily

**Comment by strideynet** [comment]
Is this a third account type? i.e Personal/Corporate/Savings? Or is it a class of account i.e Personal Savings/Personal Current/Corporate Savings/Corporate Account.

**Comment by Padanub** [comment]
tbf I think its a decision to be made, I guess it's a class of account, so you have

Personal

- Savings
- Premium
- Others

Corporate

- Just corporate?

That being said there is going to be so few types I dont think it matters maybe, would implementing it as a class or sub class be easiest?
