### ISSUE TITLE
Lottery System

### ISSUE THREAD

**Issue by Padanub** [strideynet/ModelWorld-Bank#35]
As a user I'd like to be able to take part in a lottery to win cash!

As staff I'd like to have the lottery only run when I click a button (ie it's drawn manually on friday but all the winnings are paid automatically etc)

Time: 3 hours

**Comment by strideynet** [comment]
Do we want to run a fixed term lottery? I.e We do a weekly draw on Friday?

**Comment by Padanub** [comment]
Yes

**Comment by strideynet** [comment]
One lottery or multiple lotteries?

**Comment by Padanub** [comment]
Great question, lets go for one now and see what happens

**Comment by Padanub** [comment]
oh also make it so its basically total RNG, ie it can rollover and there isn't a winner every week, like the IRL lotto

**Comment by Padanub** [comment]
Don't want this integrated, prefer user-run
