### ISSUE TITLE
Change the transactions tab on the account page.

### ISSUE THREAD

**Issue by LordTwistednuke** [strideynet/ModelWorld-Bank#42]
The listed transaction columns should read in the following order.

Amount (+£1,767.15) - replaces amount currency and positive/negative.
Date (12/01/2018, 23:09) - replace the current date format, it's a pain to read.
Total (£75,928.69) - new column, shows the resultant account total.
Description (Your wages earned from your job as a Legislative Member and CEO of dank memes inc) - Shows people what they're actually being paid for, remove the yearly wage thing it's an eyesore.

**Comment by Padanub** [comment]
Not sure what he means here
