### ISSUE TITLE
Ability to send a payment to multiple accounts (ADMIN ONLY)

### ISSUE THREAD

**Issue by Padanub** [strideynet/ModelWorld-Bank#44]
If I want to pay multiple people, can we formulate an easy way to do this? (Checkboxes or something)

**Comment by strideynet** [comment]
Rather than send one payment to multiple accounts, it will produce multiple payments to single accounts. Without rebuilding the transaction system, I am unable to pay multiple people at once.

**Comment by Padanub** [comment]
Any workaround we can think of? I know when we hit Corporate they may want to pay multiple

**Comment by Padanub** [comment]
Can we revisit this?
