### ISSUE TITLE
Mobile Warning

### ISSUE THREAD

**Issue by Padanub** [strideynet/ModelWorld-Bank#47]
Any user who access the site receives a warning telling them the site is not Mobile Optimized and features may not work as intended (because it isnt)

then they select yes or no as to wether enter the site?

**Comment by strideynet** [comment]
So you want to show this to all users, even if they may be on PC correct?

**Comment by Padanub** [comment]
uhh sorry I meant just mobile users.

Unless that is a big piece of work in which case we'll push back to UX

**Comment by Padanub** [comment]
Not received this for a while now, happy to close
