### ISSUE TITLE
Control over Taxes

### ISSUE THREAD

**Issue by Padanub** [strideynet/ModelWorld-Bank#68]
As Staff I'd like to amend the tax rates and transaction fee rates so we can keep up with the MHOC economy

1 - 1.5 hours

**Comment by strideynet** [comment]
Also adding to this task, adding transaction fee control.

**Comment by Padanub** [comment]
Can you also let me set the minimum to be taxaed (personal allowance) atm its 12k but I might wanna amend it?

**Comment by Padanub** [comment]
So we want

Income Tax Settings (both % amount and brackets, so x% for £y to £z)
Transaction Fee Settings (whether its flat or % and what it is)

**Comment by Padanub** [comment]
this again kek, so we can amend tax brackets
