### ISSUE TITLE
FAQ Update

### ISSUE THREAD

**Issue by Padanub** [strideynet/ModelWorld-Bank#76]
Please update with the below, questions are the same just answers re-worded

**Main Questions**
What is Nub International Bank?
Nub International Bank is a minigame for the Model World, simulating personal finances for all members. It is gameified so we aren't all sat here worrying about bills to pay, but there will be financial challenges, events and other games to make and lose cash!
Is this canon?
No, we do not want to make it canon either.
How do I login?
There is a button on the top right of the website which will use your Reddit account to login. We only need your basic identity data from Reddit (Join Date, Username, User ID) and will not have access to your posts or have the ability to post as you. By using OAuth2, we will never have access to your login credentials or any other personal information. However, by logging into the site you accept our terms and conditions.
How do I get an bank account?
All former ModelBarclays customers will have a bank account set up for them already, those who do not just need to PM /u/Padanub on Reddit or join the discord https://discord.gg/kCfQ9pM and request one in there.
Can I have more than one account?
Yes, although wages can only be paid into one.
Are there different types of account?
Not yet, but there will be.
The site doesn't look that appealing, Are you going to make it pretty?
We are working on a new site CSS but we don't have a specialist Web Designer so we are stuck with templates. Please drop me a message if you're able to do this.
Who do I contact for any questions not answered here?
PM /u/Padanub on Reddit or join the discord
What is NigeBot?
NigeBot is a Discord Bot we use for some injokes and memes. Once we have the site in a more advanced state NigeBot will be able to do more to integrate with the site

**Wage Questions**
How do I request wages?
Enter your bank account and on there is a link called Wages, there will be a button to request wages on there. Do not request wages for jobs you don't have, they will be declined.
Where are the wages for X?
We do allow for custom wages and soon you will be able to apply for custom wages on the site, for now any custom wage requests need to be sent to /u/Padanub via reddit or discord.
Why do Lords get the same wage as MPs?
Gamification. Lords get £300 a day and if they were to sit every day, five days a week they would be getting *roughly* what an MP gets a year so we decided for ease of use to roll it into the MP wage.
Are there pensions?
No, we currently don't have a viable way to implement pensions considering how many people are ex-ministers and the value of pensions.
How are wages paid?
Wages within NiB are designed to reflect the progression of time within the simulation of MHOC. The raw values of your wages will be totted up and then multiplied by 10 (the MHOC to IRL time multiplier). This provides a value for how much you should be paid per IRL year. We then divide this up by 365 and pay it nightly.
I'm being taxed?!? How?
Tax exists, deal with it. We base our tax rates off the most recently passed MHOC Budget and you will be taxed automatically in a similar manner to your wages.

**Feature Questions**
What can I actually do on this?
You are able to receive your wages, make bets and complete peer-2-peer transactions (Bribery, paying for services, design, consulting, advice, press appearances, cash for peers scandals, donations, money laundering, your imagination is your limit.)
What about feature X?
We currently have several features in passive development, any suggestions please forward to Padanub or the NiB Discord
What about foreign wages/currencies?	
Foreign Currency is already built into the site, however we won't be utilising it most likely until later down the line, so that cheeky job as Defence Secretary in Canada will have to wait.
Can we bet yet?
Yes, simply go to the betting page using the hyperlinks at the top! Bets will be there for your perusal.
How do we bet?
An announcement in the NiG Discord will go up when a bet is active, all you need to do is use the built in betting system!
Is there a limit on betting?
Yes, the maximum bet is £1,000,000. This is for balance reasons, any bets higher than this will be returned.

**Comment by strideynet** [comment]
Done
