### ISSUE TITLE
Fix the leaderboard

### ISSUE THREAD

**Issue by Padanub** [strideynet/ModelWorld-Bank#81]
Can we:

- Auto-sort descending balance
- Fix the rounding on the numbers
- Right-align the balances and add the pound symbol and a comma where its meant to go
- Auto-show all instead of auto show 10 (people arent realizing theres more than 10)
- Remove the description column and have it focus on name and balance
- Underneath each name can we in smaller writing show that persons highest currently individual wage (So MP, PM etc) kind of like a "primary job" thing, so it would read

Padanub                             balance here
Chairman of NubBank

**Comment by strideynet** [comment]
https://github.com/xaksis/vue-good-table
Should ideally migrate to v2 of this. This will involve redoing all the tables across the site but gives us default sort easily.

**Comment by viljow** [comment]
[leaderboard FIXED!](https://github.com/strideynet/ModelWorld-Bank-Client/pull/1)

**Comment by Padanub** [comment]
Underneath each name can we in smaller writing show that persons highest currently individual wage (So MP, PM etc) kind of like a "primary job" thing, so it would read

Padanub balance here
Chairman of NubBank

Did we work out if this was feasible?
