### ISSUE TITLE
Introduce account types and only pay wages/benefits to personal accounts

### ISSUE THREAD

**Issue by Padanub** [strideynet/ModelWorld-Bank#82]
As staff I'd like to have different account types (Personal, Company, Savings etc), so users can have a wealth of products available. (Wages/benefits only to personal accounts)

**Comment by strideynet** [comment]
alternatively, introduce account types and only pay wages to personal accounts.

**Comment by strideynet** [comment]
Only the best for you ;)

**Comment by strideynet** [comment]
https://github.com/strideynet/ModelWorld-Bank/issues/128
